### ISSUE TITLE
Can't close the box

### ISSUE THREAD

**Issue by aglpy** [JosLuna98/address_search_field#1]
Inside the function executed on field "onDone", must be a way to close the dialog, in the example it use `Navigator.of(context).pop()` but this close the hole screen not the dialog, actually the dialog still opened in the previous screen.

**Comment by JosLuna98** [comment]
It looks like maybe you are using the wrong context to make `Navigator.of(context).pop()`. Be sure to use the AddressSearchField widget, not the AddressSearchBox widget. However I added a context in the onDone function to prevent errors.
You could use `Navigator.of(dialogContext).pop()` cause onDone function declaration is `onDone(BuildContext dialogContext, AddressPoint point)` now. [Example](https://github.com/JosLuna98/address_search_field/blob/6aac97b54069e629ce7a6e23a4192f216627132c/example/lib/main.dart)
