### ISSUE TITLE
Xcode ios GeneratedPluginRegistrant.m  address_search_field' Module not found

### ISSUE THREAD

**Issue by iamkiruaa** [JosLuna98/address_search_field#10]
Hello, I use address_search_field in a project, when I build the application on xcode I get this error Module 'address_search_field' not found

I did this command but it doesn't work 

1. cd ios
2. rm -rf Pods/ Podfile.lock
3. pod install
4. flutter clean
5. flutter pub get

<img width="1512" alt="Capture d’écran 2022-02-24 à 17 07 02" src="https://user-images.githubusercontent.com/44967681/155566452-26d79086-a580-4dfc-8878-8d501adbe6b8.png">

**Comment by JosLuna98** [comment]
Hi, i guess it is because the plugin doesn't have C support. It just has swift support and i won't add retrocompatibility soon :(
You can see it in /ios/Classes/AddressSearchFieldPlugin.h file. If you want to make a change i will accept it and do a merge to the project

**Comment by Arboos-naori** [comment]
It's a flutter project, so I just build the IOS folder to send it to the apple store and I get the error above

**Comment by iamkiruaa** [comment]
It's a flutter project, so I just build the IOS folder to send it to the apple store and I get the error above

**Comment by iamkiruaa** [comment]
I tried to put the objective-C compilation to Swift but still an error 

<img width="1409" alt="Capture d’écran 2022-02-25 à 09 12 37" src="https://user-images.githubusercontent.com/44967681/155679445-e4a0e5aa-ec30-4729-8474-22046583ed48.png">
<img width="1409" alt="Capture d’écran 2022-02-25 à 09 11 15" src="https://user-images.githubusercontent.com/44967681/155679482-c15a5a26-f2a6-4374-8097-0de97c79715e.png">

o

**Comment by iamkiruaa** [comment]
<img width="1399" alt="Capture d’écran 2022-02-25 à 09 41 42" src="https://user-images.githubusercontent.com/44967681/155683576-ff036fdf-b75a-48a3-81dc-614be10cb3da.png">

**Comment by iamkiruaa** [comment]
I have solved the problem

- reinstall flutter 
- reinstall dart
- updated dependencies
- create a new ios folder
