### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by Sarat-1997** [JosLuna98/address_search_field#15]
Error in route_notifier.dart . Code:

 1. Future<void> setLocation(AddressId addressId, Address address) async {
    if (addressId == AddressId.origin) {
      _origin = address;
      _originController.text = address.reference!; // here is the error.
    } else if (addressId == AddressId.destination) {
      _destination = address;
      _destinationController.text = address.reference!;
    } else if (addressId == AddressId.waypoint) {
      addWaypoint(address);
    }
    notifyListeners();
  }

  setLocation(addressId, newAddress);//error 

Kindly solve ASAP.

**Comment by JosLuna98** [comment]
thank you, I already fix and upgrade the plugin.
