### ISSUE TITLE
Execution failed for task ':address_search_field:compileDebugKotlin'.

### ISSUE THREAD

**Issue by papamon0** [JosLuna98/address_search_field#2]
Hi!

when I launch the app get this error:

e: /flutter/.pub-cache/hosted/pub.dartlang.org/address_search_field-1.4.1/android/src/main/kotlin/dev/jostech/address_search_field/AddressSearchFieldPlugin.kt: (13, 14): Redeclaration: AddressSearchFieldPlugin
e: /flutter/.pub-cache/hosted/pub.dartlang.org/address_search_field-1.4.2/android/src/main/kotlin/dev/jostech/address_search_field/AddressSearchFieldPlugin.kt: (13, 14): Redeclaration: AddressSearchFieldPlugin

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':address_search_field:compileDebugKotlin'.

**Comment by papamon0** [comment]
I have solved the problem with:

flutter clean

**Comment by JosLuna98** [comment]
Hello!
Thanks for commenting, maybe it happened with the last update so you needed to refresh your build.
