### ISSUE TITLE
Navigator.of(dialogContext).pop() should be working onCleaned

### ISSUE THREAD

**Issue by sohelpathan** [JosLuna98/address_search_field#3]
I'm setting coordinates on maps using marker in next screen.  But onCleaned does not pop from navigation.

**Comment by JosLuna98** [comment]
When you press the submit button on addressSearchBar, it tries to find the correct address name and coordinates, but if the addressSearchBar field is empty, it will execute the onCleaned function to do what you program. I added dialogContext only in onDone function to avoid problems with context, so you could just use Navigator.of(context).pop() if you need to dismiss the widget.

But if it doesn't work, tell me. And if you think I should add it also tell me why :)
