### ISSUE TITLE
The method 'AddressSearchField' isn't defined for the class '_MapedState'.

### ISSUE THREAD

**Issue by galopianciola** [JosLuna98/address_search_field#5]
Hi, i'm having a problem with this module

```
    lib/Screens/Delivery/widget/map.dart:1045:58: Error: **'AddressPoint' isn't a type.**
                                (BuildContext dialogContext, AddressPoint point) {
                                                             ^^^^^^^^^^^^
    lib/Screens/Delivery/widget/map.dart:1010:30: Error: **The method 'AddressSearchField' isn't defined for the class '_MapedState'.**
     - '_MapedState' is from 'package:bellava/Screens/Delivery/widget/map.dart' ('lib/Screens/Delivery/widget/map.dart').
    Try correcting the name to the name of an existing method, or defining a method named 'AddressSearchField'.
                          child: AddressSearchField(
```

It happens when I try to do the **flutter build ios**
It would be really helpful for me if u can give me any advice

**Comment by JosLuna98** [comment]
Hi, are you specifing the plugin version in your pubspec.yaml file?
AddressPoint is a type from 1.4.2 version, from 2.0.0 it just uses Address as type.
You can specify the plugin version in 1.4.2 to continue using their types or update to the actual 3.0.3+1 version but it has breaking changes.

**Comment by galopianciola** [comment]
Thanks for helping me! This problem got me in trouble since weeks ago
Specifying 1.4.2 version solved the type problem, now AddressPoint is a valid type
But I have this problem now, as I had some time ago too

`    /Users/macbook/Documents/developer/bellava/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module 'address_search_field' not found
    @import address_search_field;`

It's in GeneratedPluginRegistrant.m, Runner folder:

`#import "GeneratedPluginRegistrant.h"

#if __has_include(<address_search_field/AddressSearchFieldPlugin.h>)
#import <address_search_field/AddressSearchFieldPlugin.h>
#else
@import address_search_field;
#endif`

**Comment by JosLuna98** [comment]
Mmm i'm pretty sure it happends 'cause you still have the new plugin version in your `GeneratedPluginRegistrant.m` file.
I have had this problem before, but i don't remember how to solve it, you should try doing a `flutter clean` or search how to update the ios pod, it's something like run `pod install` command in `ios/` folder.

**Comment by galopianciola** [comment]
Yes, that one may be the problem, the plugin version in that file, sure.
I've tested both alternatives (_flutter clean_ and _pod install_) you gave me but it still doesn't work.
I'll keep on trying with other alternatives.
Thanks for the help, and please tell me then if you remember how u solved it haha

**Comment by JosLuna98** [comment]
It's a problem in your project with the ios part, the path is from your project and not from the plugin hosted in `pub-cache`.
Time ago i have had a problem like this and i used `flutter clean` and `pod install` and other commands but i can remember that i finally created a new project with the same name and copy and paste all my code 'cause is very hard for me solve issues with gradle (android) and pod (ios).
I know it's not the most professional solve but... it's easy hehe.

**Comment by galopianciola** [comment]
Thank you JosLuna98!
I’m gonna test that and I’m pretty sure it’ll solve it.
