### ISSUE TITLE
Execution failed for task ':address_search_field:verifyReleaseResources'.

### ISSUE THREAD

**Issue by bryanus1** [JosLuna98/address_search_field#6]
Hi, I'm working to app and add this dependence. it's worked well but from updated flutter i can't generated a apk.

When generated apk flutter show me this: 
You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64,android-x64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':address_search_field:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Path '/Volumes/INFO/Beux/client_app/build/flutter_plugin_android_lifecycle/intermediates/compiled_local_resources/release/out' is not a readable directory.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                      16.0s
Gradle task assembleRelease failed with exit code 1

flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-CO)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.52.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by JosLuna98** [comment]
Hi, I understand that you are here 'cause it says:
>What went wrong:
Execution failed for task ':address_search_field:verifyReleaseResources'.

But I saw this:
>A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
Path '/Volumes/INFO/Beux/client_app/build/flutter_plugin_android_lifecycle/intermediates/compiled_local_resources/release/out' is not a readable directory.

So, i suggest you run **flutter clean** and try to build the apk again 'cause it seems to be a directory problem.

Eso de readable directory me parece que es porque no se puede escribir en ese directorio que esta dentro de tu carpeta build, la cual se genera cuando ejecutas el comando **flutter build apk**, entonces prueba a hacer el **flutter clean** para que se borre y vuelve a intentar compilar. Me parece que no es problema del plugin, sin embargo, no dudes en comentar nuevamente.
