### ISSUE TITLE
Can we make city parameter for GeoMethods optional?

### ISSUE THREAD

**Issue by ShaneZhengNZ** [JosLuna98/address_search_field#7]
When searching for an address, the city is not always available. can we make city parameter optional? At the moment, the workaround is to pass an empty string. It works, but a little ugly.

**Comment by JosLuna98** [comment]
Hello! Yes, people had already told me about that detail before. I already made the change (66803c8494864d459c2c6f20f2c561b653265e91).
There are still more ideas to improve the plugin, they will be implemented soon :)
Thanks for your advice
